// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file common.proto (package whirled2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common.proto.
 */
export const file_common: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SCHdoaXJsZWQyItoBCgZQbGF5ZXISEAoIdXNlcm5hbWUYASABKAkSEAoIbmlja25hbWUYAiABKAkSDAoEZmlsZRgDIAEoCRINCgVsb2NhbBgEIAEoCBINCgVvd25lchgFIAEoCBIkCghwb3NpdGlvbhgGIAEoCzISLndoaXJsZWQyLlBvc2l0aW9uEiQKCHJvdGF0aW9uGAcgASgLMhIud2hpcmxlZDIuUm90YXRpb24SHgoFc2NhbGUYCCABKAsyDy53aGlybGVkMi5TY2FsZRIUCgxpbml0aWFsU2NhbGUYCSABKAEi4QEKBk9iamVjdBIKCgJpZBgBIAEoCRIcCgR0eXBlGAIgASgOMg4ud2hpcmxlZDIuVHlwZRIPCgdzdHVmZklkGAMgASgJEgwKBG5hbWUYBCABKAkSDAoEZmlsZRgFIAEoCRIkCghwb3NpdGlvbhgGIAEoCzISLndoaXJsZWQyLlBvc2l0aW9uEiQKCHJvdGF0aW9uGAcgASgLMhIud2hpcmxlZDIuUm90YXRpb24SHgoFc2NhbGUYCCABKAsyDy53aGlybGVkMi5TY2FsZRIUCgxpbml0aWFsU2NhbGUYCSABKAEiKwoIUG9zaXRpb24SCQoBeBgBIAEoARIJCgF5GAIgASgBEgkKAXoYAyABKAEiNgoIUm90YXRpb24SCQoBeBgBIAEoARIJCgF5GAIgASgBEgkKAXoYAyABKAESCQoBdxgEIAEoASIoCgVTY2FsZRIJCgF4GAEgASgBEgkKAXkYAiABKAESCQoBehgDIAEoASorCgRUeXBlEggKBE5vbmUQABIKCgZBdmF0YXIQARINCglGdXJuaXR1cmUQAkIWWhR3aGlybGVkMi91dGlscy9wcm90b2IGcHJvdG8z");

/**
 * @generated from message whirled2.Player
 */
export type Player = Message<"whirled2.Player"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string nickname = 2;
   */
  nickname: string;

  /**
   * @generated from field: string file = 3;
   */
  file: string;

  /**
   * @generated from field: bool local = 4;
   */
  local: boolean;

  /**
   * is owner of current room
   *
   * @generated from field: bool owner = 5;
   */
  owner: boolean;

  /**
   * @generated from field: whirled2.Position position = 6;
   */
  position?: Position;

  /**
   * @generated from field: whirled2.Rotation rotation = 7;
   */
  rotation?: Rotation;

  /**
   * @generated from field: whirled2.Scale scale = 8;
   */
  scale?: Scale;

  /**
   * @generated from field: double initialScale = 9;
   */
  initialScale: number;
};

/**
 * Describes the message whirled2.Player.
 * Use `create(PlayerSchema)` to create a new message.
 */
export const PlayerSchema: GenMessage<Player> = /*@__PURE__*/
  messageDesc(file_common, 0);

/**
 * @generated from message whirled2.Object
 */
export type Object$ = Message<"whirled2.Object"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: whirled2.Type type = 2;
   */
  type: Type;

  /**
   * @generated from field: string stuffId = 3;
   */
  stuffId: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string file = 5;
   */
  file: string;

  /**
   * @generated from field: whirled2.Position position = 6;
   */
  position?: Position;

  /**
   * @generated from field: whirled2.Rotation rotation = 7;
   */
  rotation?: Rotation;

  /**
   * @generated from field: whirled2.Scale scale = 8;
   */
  scale?: Scale;

  /**
   * @generated from field: double initialScale = 9;
   */
  initialScale: number;
};

/**
 * Describes the message whirled2.Object.
 * Use `create(ObjectSchema)` to create a new message.
 */
export const ObjectSchema: GenMessage<Object$> = /*@__PURE__*/
  messageDesc(file_common, 1);

/**
 * @generated from message whirled2.Position
 */
export type Position = Message<"whirled2.Position"> & {
  /**
   * @generated from field: double x = 1;
   */
  x: number;

  /**
   * @generated from field: double y = 2;
   */
  y: number;

  /**
   * @generated from field: double z = 3;
   */
  z: number;
};

/**
 * Describes the message whirled2.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_common, 2);

/**
 * @generated from message whirled2.Rotation
 */
export type Rotation = Message<"whirled2.Rotation"> & {
  /**
   * @generated from field: double x = 1;
   */
  x: number;

  /**
   * @generated from field: double y = 2;
   */
  y: number;

  /**
   * @generated from field: double z = 3;
   */
  z: number;

  /**
   * @generated from field: double w = 4;
   */
  w: number;
};

/**
 * Describes the message whirled2.Rotation.
 * Use `create(RotationSchema)` to create a new message.
 */
export const RotationSchema: GenMessage<Rotation> = /*@__PURE__*/
  messageDesc(file_common, 3);

/**
 * @generated from message whirled2.Scale
 */
export type Scale = Message<"whirled2.Scale"> & {
  /**
   * @generated from field: double x = 1;
   */
  x: number;

  /**
   * @generated from field: double y = 2;
   */
  y: number;

  /**
   * @generated from field: double z = 3;
   */
  z: number;
};

/**
 * Describes the message whirled2.Scale.
 * Use `create(ScaleSchema)` to create a new message.
 */
export const ScaleSchema: GenMessage<Scale> = /*@__PURE__*/
  messageDesc(file_common, 4);

/**
 * @generated from enum whirled2.Type
 */
export enum Type {
  /**
   * @generated from enum value: None = 0;
   */
  None = 0,

  /**
   * @generated from enum value: Avatar = 1;
   */
  Avatar = 1,

  /**
   * @generated from enum value: Furniture = 2;
   */
  Furniture = 2,
}

/**
 * Describes the enum whirled2.Type.
 */
export const TypeSchema: GenEnum<Type> = /*@__PURE__*/
  enumDesc(file_common, 0);

