// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file message.proto (package whirled2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PlayerAnim, PlayerAuth, PlayerChat, PlayerJoin, PlayerLeave, PlayerMove, PlayerWear } from "./player_pb";
import { file_player } from "./player_pb";
import type { ObjectJoin, ObjectLeave, ObjectTransform } from "./object_pb";
import { file_object } from "./object_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file message.proto.
 */
export const file_message: GenFile = /*@__PURE__*/
  fileDesc("Cg1tZXNzYWdlLnByb3RvEgh3aGlybGVkMiLdAwoMV2hpcmxlZEV2ZW50EioKCnBsYXllckF1dGgYASABKAsyFC53aGlybGVkMi5QbGF5ZXJBdXRoSAASKgoKcGxheWVySm9pbhgCIAEoCzIULndoaXJsZWQyLlBsYXllckpvaW5IABIsCgtwbGF5ZXJMZWF2ZRgDIAEoCzIVLndoaXJsZWQyLlBsYXllckxlYXZlSAASKgoKcGxheWVyQ2hhdBgEIAEoCzIULndoaXJsZWQyLlBsYXllckNoYXRIABIqCgpwbGF5ZXJNb3ZlGAUgASgLMhQud2hpcmxlZDIuUGxheWVyTW92ZUgAEioKCnBsYXllckFuaW0YBiABKAsyFC53aGlybGVkMi5QbGF5ZXJBbmltSAASKgoKcGxheWVyV2VhchgHIAEoCzIULndoaXJsZWQyLlBsYXllcldlYXJIABIqCgpvYmplY3RKb2luGAggASgLMhQud2hpcmxlZDIuT2JqZWN0Sm9pbkgAEiwKC29iamVjdExlYXZlGAkgASgLMhUud2hpcmxlZDIuT2JqZWN0TGVhdmVIABI0Cg9vYmplY3RUcmFuc2Zvcm0YCiABKAsyGS53aGlybGVkMi5PYmplY3RUcmFuc2Zvcm1IAEIHCgVldmVudEIWWhR3aGlybGVkMi91dGlscy9wcm90b2IGcHJvdG8z", [file_player, file_object]);

/**
 * @generated from message whirled2.WhirledEvent
 */
export type WhirledEvent = Message<"whirled2.WhirledEvent"> & {
  /**
   * @generated from oneof whirled2.WhirledEvent.event
   */
  event: {
    /**
     * @generated from field: whirled2.PlayerAuth playerAuth = 1;
     */
    value: PlayerAuth;
    case: "playerAuth";
  } | {
    /**
     * @generated from field: whirled2.PlayerJoin playerJoin = 2;
     */
    value: PlayerJoin;
    case: "playerJoin";
  } | {
    /**
     * @generated from field: whirled2.PlayerLeave playerLeave = 3;
     */
    value: PlayerLeave;
    case: "playerLeave";
  } | {
    /**
     * @generated from field: whirled2.PlayerChat playerChat = 4;
     */
    value: PlayerChat;
    case: "playerChat";
  } | {
    /**
     * @generated from field: whirled2.PlayerMove playerMove = 5;
     */
    value: PlayerMove;
    case: "playerMove";
  } | {
    /**
     * @generated from field: whirled2.PlayerAnim playerAnim = 6;
     */
    value: PlayerAnim;
    case: "playerAnim";
  } | {
    /**
     * @generated from field: whirled2.PlayerWear playerWear = 7;
     */
    value: PlayerWear;
    case: "playerWear";
  } | {
    /**
     * @generated from field: whirled2.ObjectJoin objectJoin = 8;
     */
    value: ObjectJoin;
    case: "objectJoin";
  } | {
    /**
     * @generated from field: whirled2.ObjectLeave objectLeave = 9;
     */
    value: ObjectLeave;
    case: "objectLeave";
  } | {
    /**
     * @generated from field: whirled2.ObjectTransform objectTransform = 10;
     */
    value: ObjectTransform;
    case: "objectTransform";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message whirled2.WhirledEvent.
 * Use `create(WhirledEventSchema)` to create a new message.
 */
export const WhirledEventSchema: GenMessage<WhirledEvent> = /*@__PURE__*/
  messageDesc(file_message, 0);

