// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file object.proto (package whirled2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Object$, Position, Rotation, Scale } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file object.proto.
 */
export const file_object: GenFile = /*@__PURE__*/
  fileDesc("CgxvYmplY3QucHJvdG8SCHdoaXJsZWQyIi4KCk9iamVjdEpvaW4SIAoGb2JqZWN0GAEgASgLMhAud2hpcmxlZDIuT2JqZWN0IisKC09iamVjdExlYXZlEgoKAmlkGAEgASgJEhAKCGlzUGxheWVyGAIgASgIIpsBCg9PYmplY3RUcmFuc2Zvcm0SCgoCaWQYASABKAkSEAoIaXNQbGF5ZXIYAiABKAgSJAoIcG9zaXRpb24YAyABKAsyEi53aGlybGVkMi5Qb3NpdGlvbhIkCghyb3RhdGlvbhgEIAEoCzISLndoaXJsZWQyLlJvdGF0aW9uEh4KBXNjYWxlGAUgASgLMg8ud2hpcmxlZDIuU2NhbGVCFloUd2hpcmxlZDIvdXRpbHMvcHJvdG9iBnByb3RvMw", [file_common]);

/**
 * @generated from message whirled2.ObjectJoin
 */
export type ObjectJoin = Message<"whirled2.ObjectJoin"> & {
  /**
   * @generated from field: whirled2.Object object = 1;
   */
  object?: Object$;
};

/**
 * Describes the message whirled2.ObjectJoin.
 * Use `create(ObjectJoinSchema)` to create a new message.
 */
export const ObjectJoinSchema: GenMessage<ObjectJoin> = /*@__PURE__*/
  messageDesc(file_object, 0);

/**
 * @generated from message whirled2.ObjectLeave
 */
export type ObjectLeave = Message<"whirled2.ObjectLeave"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: bool isPlayer = 2;
   */
  isPlayer: boolean;
};

/**
 * Describes the message whirled2.ObjectLeave.
 * Use `create(ObjectLeaveSchema)` to create a new message.
 */
export const ObjectLeaveSchema: GenMessage<ObjectLeave> = /*@__PURE__*/
  messageDesc(file_object, 1);

/**
 * @generated from message whirled2.ObjectTransform
 */
export type ObjectTransform = Message<"whirled2.ObjectTransform"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: bool isPlayer = 2;
   */
  isPlayer: boolean;

  /**
   * @generated from field: whirled2.Position position = 3;
   */
  position?: Position;

  /**
   * @generated from field: whirled2.Rotation rotation = 4;
   */
  rotation?: Rotation;

  /**
   * @generated from field: whirled2.Scale scale = 5;
   */
  scale?: Scale;
};

/**
 * Describes the message whirled2.ObjectTransform.
 * Use `create(ObjectTransformSchema)` to create a new message.
 */
export const ObjectTransformSchema: GenMessage<ObjectTransform> = /*@__PURE__*/
  messageDesc(file_object, 2);

