// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file player.proto (package whirled2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Player, Position, Rotation } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file player.proto.
 */
export const file_player: GenFile = /*@__PURE__*/
  fileDesc("CgxwbGF5ZXIucHJvdG8SCHdoaXJsZWQyIi4KClBsYXllckpvaW4SIAoGcGxheWVyGAEgASgLMhAud2hpcmxlZDIuUGxheWVyIh8KC1BsYXllckxlYXZlEhAKCHVzZXJuYW1lGAEgASgJIjQKClBsYXllckF1dGgSCgoCaWQYASABKAkSDAoEY29kZRgCIAEoCRIMCgRyb29tGAMgASgJIi8KClBsYXllckNoYXQSEAoIdXNlcm5hbWUYASABKAkSDwoHbWVzc2FnZRgCIAEoCSJqCgpQbGF5ZXJNb3ZlEhAKCHVzZXJuYW1lGAEgASgJEiQKCHBvc2l0aW9uGAIgASgLMhIud2hpcmxlZDIuUG9zaXRpb24SJAoIcm90YXRpb24YAyABKAsyEi53aGlybGVkMi5Sb3RhdGlvbiIsCgpQbGF5ZXJBbmltEhAKCHVzZXJuYW1lGAEgASgJEgwKBGFuaW0YAiABKAkiRwoKUGxheWVyV2VhchIQCgh1c2VybmFtZRgBIAEoCRIKCgJpZBgCIAEoCRIMCgRmaWxlGAMgASgJEg0KBXNjYWxlGAQgASgBQhZaFHdoaXJsZWQyL3V0aWxzL3Byb3RvYgZwcm90bzM", [file_common]);

/**
 * @generated from message whirled2.PlayerJoin
 */
export type PlayerJoin = Message<"whirled2.PlayerJoin"> & {
  /**
   * @generated from field: whirled2.Player player = 1;
   */
  player?: Player;
};

/**
 * Describes the message whirled2.PlayerJoin.
 * Use `create(PlayerJoinSchema)` to create a new message.
 */
export const PlayerJoinSchema: GenMessage<PlayerJoin> = /*@__PURE__*/
  messageDesc(file_player, 0);

/**
 * @generated from message whirled2.PlayerLeave
 */
export type PlayerLeave = Message<"whirled2.PlayerLeave"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message whirled2.PlayerLeave.
 * Use `create(PlayerLeaveSchema)` to create a new message.
 */
export const PlayerLeaveSchema: GenMessage<PlayerLeave> = /*@__PURE__*/
  messageDesc(file_player, 1);

/**
 * @generated from message whirled2.PlayerAuth
 */
export type PlayerAuth = Message<"whirled2.PlayerAuth"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * @generated from field: string room = 3;
   */
  room: string;
};

/**
 * Describes the message whirled2.PlayerAuth.
 * Use `create(PlayerAuthSchema)` to create a new message.
 */
export const PlayerAuthSchema: GenMessage<PlayerAuth> = /*@__PURE__*/
  messageDesc(file_player, 2);

/**
 * @generated from message whirled2.PlayerChat
 */
export type PlayerChat = Message<"whirled2.PlayerChat"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message whirled2.PlayerChat.
 * Use `create(PlayerChatSchema)` to create a new message.
 */
export const PlayerChatSchema: GenMessage<PlayerChat> = /*@__PURE__*/
  messageDesc(file_player, 3);

/**
 * @generated from message whirled2.PlayerMove
 */
export type PlayerMove = Message<"whirled2.PlayerMove"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: whirled2.Position position = 2;
   */
  position?: Position;

  /**
   * @generated from field: whirled2.Rotation rotation = 3;
   */
  rotation?: Rotation;
};

/**
 * Describes the message whirled2.PlayerMove.
 * Use `create(PlayerMoveSchema)` to create a new message.
 */
export const PlayerMoveSchema: GenMessage<PlayerMove> = /*@__PURE__*/
  messageDesc(file_player, 4);

/**
 * @generated from message whirled2.PlayerAnim
 */
export type PlayerAnim = Message<"whirled2.PlayerAnim"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string anim = 2;
   */
  anim: string;
};

/**
 * Describes the message whirled2.PlayerAnim.
 * Use `create(PlayerAnimSchema)` to create a new message.
 */
export const PlayerAnimSchema: GenMessage<PlayerAnim> = /*@__PURE__*/
  messageDesc(file_player, 5);

/**
 * @generated from message whirled2.PlayerWear
 */
export type PlayerWear = Message<"whirled2.PlayerWear"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string file = 3;
   */
  file: string;

  /**
   * @generated from field: double scale = 4;
   */
  scale: number;
};

/**
 * Describes the message whirled2.PlayerWear.
 * Use `create(PlayerWearSchema)` to create a new message.
 */
export const PlayerWearSchema: GenMessage<PlayerWear> = /*@__PURE__*/
  messageDesc(file_player, 6);

