# fly.toml app configuration file generated for whirled2 on 2024-04-12T01:09:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whirled2'
primary_region = 'sjc'

[build]

[mounts]
  destination = "/app/pb_data"
  source = "pb_data"

[http_service]
  internal_port = 42069
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 42069
  protocol = "udp"

  [[services.ports]]
    port = "42069"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
